services:
  servermonitor:
    build: .
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:8080
      - ConnectionStrings__MarketDataConnection=Host=localhost;Database=marketdata;Username=postgres;Password=postBlack77;Port=5432